apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: wordpress-namespace
spec:
  storageClassName: ""
  volumeName: mysql-pv # Asociado con el PV estático
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
      